Cleanup bash script header, update alias for VBoxManage

diff --git a/vim/bash-support/templates/bash.comments.template b/vim/bash-support/templates/bash.comments.template
--- a/vim/bash-support/templates/bash.comments.template
+++ b/vim/bash-support/templates/bash.comments.template
@@ -11,67 +11,64 @@
 # RETURN: 
 §%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 == comment.file-description == start ==
-#!/bin/bash
-#  DETAILS: <CURSOR>
-#  CREATED: |DATE| |TIME|
-# MODIFIED: |DATE| |TIME|
-# REVISION: 1.0
+##!/bin/bash
+##  DETAILS: <CURSOR>
+##  CREATED: |DATE| |TIME|
+## MODIFIED: |DATE| |TIME|
+## REVISION: 1.0
+##
+##   AUTHOR: |AUTHOR|, |EMAIL|
+##  LICENCE: |COPYRIGHT|
 #
-#   AUTHOR: |AUTHOR|, |EMAIL|
-#  LICENCE: |COPYRIGHT|
-
-#set -uvx   # Warn unset vars, Verbose (echo each command), Enable debug mode
-
-PATH=/usr/bin:/usr/sbin:.:/auto/opt/bin:/bin
-
-if [ "|FILENAME|" == "$(basename $0)" ] && [ -f $HOME/.bashrc ]; then
-	source $HOME/.bashrc
-	log_init INFO $SCRIPT_LOGS/|FILENAME|.log
-fi
-
-usage()
-{
-	echo "Usage: |FILENAME| [-h|]"
-	echo "Options:"
-	echo "  -h          - print this help"
-}
-
-# Each shell script has to be independently testable.
-# It can then be included in other files for functions.
-main()
-{
-    PARSE_OPTS="h"
-    local opts_found=0
-    while getopts ":$PARSE_OPTS" opt; do
-		case $opt in
-			[a-zA-Z0-9])
-			log DEBUG "-$opt was triggered, Parameter: $OPTARG"
-			local "opt_$opt"=1 && local "optarg_$opt"="$OPTARG"
-			;;
-		\?)
-			echo "Invalid option: -$OPTARG"; usage; exit $EINVAL
-			;;
-		:)
-			echo "[ERROR] Option -$OPTARG requires an argument";
-			usage; exit $EINVAL
-			;;
-		esac
-		shift $((OPTIND-1)) && OPTIND=1 && local opts_found=1;
-    done
-
-	if ((!opts_found)); then
-		usage && exit $EINVAL;
-	fi
-
-	((opt_h)) && { usage; }
-
-    exit 0;
-}
-
-if [ "|FILENAME|" == "$(basename $0)" ]; then
-	main $*
-fi
-# VIM: ts=4:sw=4:sts=4:expandtab
+##set -uvx   # Warn unset vars, Verbose (echo each command), Enable debug mode
+#
+#PATH=/usr/bin:/usr/sbin:.:/auto/opt/bin:/bin
+#
+#[[ "$(basename |FILENAME|)" == "$(basename -- $0)" && -f $HOME/.bashrc.dev ]] && { source $HOME/.bashrc.dev; }
+#
+#usage()
+#{
+#    echo "Usage: |FILENAME| [-h|]"
+#    echo "Options:"
+#    echo "  -h          - print this help"
+#}
+#
+## Each shell script has to be independently testable.
+## It can then be included in other files for functions.
+#main()
+#{
+#    PARSE_OPTS="h"
+#    local opts_found=0
+#    while getopts ":$PARSE_OPTS" opt; do
+#        case $opt in
+#        [a-zA-Z0-9])
+#            log DEBUG "-$opt was triggered, Parameter: $OPTARG"
+#            local "opt_$opt"=1 && local "optarg_$opt"="$OPTARG"
+#            ;;
+#        \?)
+#            echo "Invalid option: -$OPTARG"; usage; exit $EINVAL
+#            ;;
+#        :)
+#            echo "[ERROR] Option -$OPTARG requires an argument";
+#            usage; exit $EINVAL
+#            ;;
+#        esac
+#        shift $((OPTIND-1)) && OPTIND=1 && local opts_found=1;
+#    done
+#
+#    if ((!opts_found)); then
+#        usage && exit $EINVAL;
+#    fi
+#
+#    ((opt_h)) && { usage; }
+#
+#    exit 0;
+#}
+#
+#if [ "|FILENAME|" == "$(basename $0)" ]; then
+#    main $*
+#fi
+## VIM: ts=4:sw=4:sts=4:expandtab
 §%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 == comment.keyword-bug == append ==
  # :BUG:|DATE| |TIME|:|AUTHORREF|: <CURSOR>
